### PR TITLE
Add Gaurav_Saha.md file to '_hackbars' directory

### PR DESCRIPTION
**Pull request by Gauravsaha-97**

### CODE REVIEW

**Comment by tasnimzotder** [comment]
hey @Gauravsaha-97 there is a conflicting file `javascript/calculations.js` with the commit `Completed the functions Add, Subtract, Multiply and Divide`. You need to remove the commit to resolve the conflict. You can do this by following commands - 

1. Remove the last 2 commits
```bash
git reset --soft HEAD~2
```

2. Reset the file `javascript/calculations.js`
```bash
git reset javascript/calculations.js
```

3. Commit your code
```bash
git commit -m " ... MESSAGE ... "
```

4. Push the changes
```bash
git push -f origin gaurav
```

**Comment by Gauravsaha-97** [comment]
@tasnimzotder I have done that.

**Comment by tasnimzotder** [comment]
Thanks @Gauravsaha-97

**Comment by Gauravsaha-97** [comment]
Most welcome @tasnimzotder

**Review by tasnimzotder — APPROVED** [review]
👍

**Pull request merged**
