### PR TITLE
Added muhammad_haseeb.md

### PR DESCRIPTION
**Pull request by haseeb1009**
added muhammad_haseeb.md file

### CODE REVIEW

**Review by tasnimzotder — APPROVED** [review]
👍

**Comment by haseeb1009** [comment]
I forgot to mention that it should be merged after October 1st.

**Comment by tasnimzotder** [comment]
@haseeb1009 Sorry to hear that.
The repository got a major update with `climate-change` theme. You can update your `hackbar` as per the requirement and open a new `PR` again.

**Comment by haseeb1009** [comment]
@tasnimzotder  Thanks for letting me know. Will update and open another PR.

**Pull request merged**
