### PR TITLE
Stack & Queue Implementation in Python

### PR DESCRIPTION
**Pull request by vighneshdeepweb**
Stack & Queue Implementation in Python @Hacktoberfest-2020 always open to open source contribution...
pls accept my PR

### CODE REVIEW

**Comment by vighneshdeepweb** [comment]
pls review my PR

**Comment by vighneshdeepweb** [comment]
so will my PR will be merged??

**Comment by vighneshdeepweb** [comment]
Do I have to give another PR with greetings onto it???

**Comment by vighneshdeepweb** [comment]
Issuing another PR with greeting onto it...

**Comment by tasnimzotder** [comment]
> so will my PR will be merged??

There some steps to complete before the merging of a PR. And those stapes take some time.
According to the guideline we've to perform those steps.

@vighneshdeepweb After the successful checks, your PR will be merged

**Comment by vighneshdeepweb** [comment]
so i guess after the review my PR will be accepted and then only it will be merged...

**Comment by vighneshdeepweb** [comment]
And approx how much time it takes??

**Review by tasnimzotder — APPROVED** [review]
Thanks @vighneshdeepweb for your contribution :)

**Comment by vighneshdeepweb** [comment]
Your welcome buddy!!!

**Pull request merged**
