### PR TITLE
Add compute.py for Electrostatic Force Calculator (GUI)

### PR DESCRIPTION
**Pull request by Priyanshu729**
RUN BOTH i.e ELECTROSTATIC FORCE.PY AND COMPUTE.PY IN THE SAME FILE.PLEASE REVIEW HOW IT'S LOOKS.

### CODE REVIEW

**Comment by Priyanshu729** [comment]
Please review my request

**Comment by Priyanshu729** [comment]
Can u accept this ?? Or reject??

**Review by tasnimzotder — APPROVED** [review]
🎉

**Comment by tasnimzotder** [comment]
image
image

**Pull request merged**
