### PR TITLE
Add Muskan's Hackbar

### PR DESCRIPTION
**Pull request by Musu1**

### CODE REVIEW

**Review by tasnimzotder — CHANGES_REQUESTED** [review]
hey @Musu1, we appreciate your effort. But you added the hackbar texts without the image.

To make this a valid PR, you need to add an image (on climate change) and link it to the hackbar texts. For more details, have a look at the documentation.

**Comment by Musu1** [comment]
Added an image

**Comment by tasnimzotder** [comment]
You have included the link of the image. You need to download and add the the `assets/images/` directory and put the image path on the `.md` file.

**Comment by Musu1** [comment]
Have put a image in assets folder and linked to md file

**Review by tasnimzotder — APPROVED** [review]

**Comment by tasnimzotder** [comment]
Thanks @Musu1, for your interest and contributions :)

**Pull request merged**
