### PR TITLE
Add heapSort in Python folder

### PR DESCRIPTION
**Pull request by kirtish16**
Heap sort function to sort elements in an array.

### CODE REVIEW

**Comment by kirtish16** [comment]
I wanted to add the .cpp file to the cpp folder but it got attached in the same pull requests which I had made earlier. Can anybody help?

**Comment by tasnimzotder** [comment]
@kirtish16, you can delete the `.cpp` file and after merging this `PR`, you can open another `PR` with that `.cpp` file

**Comment by kirtish16** [comment]
Thank you for guiding me through this. I have deleted .cpp file.

**Review by tasnimzotder — APPROVED** [review]

**Comment by tasnimzotder** [comment]
Now you can open a PR with the `.cpp` file

**Pull request merged**
