### PR TITLE
Rishav_Jaiswal.md Added

### PR DESCRIPTION
**Pull request by rishavjaiss**
Hi,

Please merge this pr on or after 1st October during Hacktoberfest.

Thanks.

### CODE REVIEW

**Review by tasnimzotder — CHANGES_REQUESTED** [review]
Remove `.gitignore` and make a `commit`

**Comment by rishavjaiss** [comment]
Hi, It is now removed. Please merge on 1st Oct or later.

**Review by tasnimzotder — APPROVED** [review]

**Comment by rishavjaiss** [comment]
Please merge on or after 1st October.

**Comment by tasnimzotder** [comment]
@rishavjaiss Okay. We'll do so.

**Comment by rishavjaiss** [comment]
Hey,
Please review this pr and merge it. Thanks!

**Review by tasnimzotder — APPROVED** [review]

**Comment by rishavjaiss** [comment]
Hey even after successful merge my pr count in hacktoberfest didn't go up. Why?

**Comment by tasnimzotder** [comment]
@rishavjaiss [Maybe] the reason is that you opened the `PR` #31 before October.
To get a `Hacktoberfest` count you need to open `PR` between 1-31 October.

**Pull request merged**
