### PR TITLE
add Rebai's hackbar

### PR DESCRIPTION
**Pull request by Rebaiahmed**
My First pull request to hacktoberfest-2020

### CODE REVIEW

**Review by tasnimzotder — APPROVED** [review]

**Comment by tasnimzotder** [comment]
Thanks for your contributions :)

**Comment by Rebaiahmed** [comment]
Hi @tasnimzotder , Can you help me to suggest other project contributions, and I have a question my MR is now until review bu Hacktoberfest until 14 days and the event will be ended in 3 days ago! so I still concerned about the challenge?

**Comment by tasnimzotder** [comment]
@Rebaiahmed, there are lots of projects for `hacktoberfest`. You can find them on https://github.com/topics/hacktoberfest or https://github.com/topics/good-first-issue.

The maturation period for your PRs should show 3-5 days depending on your region. If it's showing 14 days, then some issue might be there. Wait for a few hours and try to re-login.

Let me know if you get any issue.

**Comment by Rebaiahmed** [comment]
Hi @tasnimzotder it still 13 days event they are approved :/  , if they still in review after 31 October I will be out of the challenge?

**Pull request merged**
