### PR TITLE
Added Climate_Change_Factor.py and Simplified view of getLiveCovidData.py

### PR DESCRIPTION
**Pull request by YASHBRO**
Added `Climate_Change_Factor.py` which show live stats about the top 10 countries in:

1. Population
2. CO2 emission 
3. CFC consumption
4. Plastic waste pollution

And edited a `getLiveCovidData.py` file which shows live COVID-19 stats for a simplified view

### CODE REVIEW

**Comment by YASHBRO** [comment]
### Please review my request and accept it if you find it up to your standards as my file is very much related to the topic Climate change

**Comment by tasnimzotder** [comment]
@YASHBRO Your contributions are awesome and you're welcome to contribute more.

The review process is taking time due to the shortage of time and less number of maintainers/collaborators.

**Review by tasnimzotder — APPROVED** [review]

**Comment by YASHBRO** [comment]
Can you please add the label "Hacktoberfest accepted" in my pull request as my PR is in the review period and will only be accepted if you add the above label

PR 1 in review period

**Comment by tasnimzotder** [comment]
image
@YASHBRO It's saying that `PR` needs to be `merged`, `approved` or labelled as `hacktoberfest-accepted`.
Don't worry I'll add the label.

**Comment by YASHBRO** [comment]
> image
> @YASHBRO It's saying that `PR` needs to be `merged`, `approved` or labelled as `hacktoberfest-accepted`.
> Don't worry I'll add the label.

**Thanks**
But what is that 'Mature in:' count down?
Actually its my 1st time participation in the hacktoberfest so i don't know much.

**Comment by tasnimzotder** [comment]
@YASHBRO 
`Mature` time is a countdown (review period). In this period, if the maintainer(s) of the repo do not `approve` the `PR` or labelled as `invalid`, then the `PR` will not count towards Hacktoberfest. Otherwise, after the review period, the `PR` will be accepted.

**Comment by YASHBRO** [comment]
> @YASHBRO
> `Mature` time is a countdown (review period). In this period, if the maintainer(s) of the repo do not `approve` the `PR` or labelled as `invalid`, then the `PR` will not count towards Hacktoberfest. Otherwise, after the review period, the `PR` will be accepted.

Ohhh
**Thanks 👍**

**Pull request merged**
