### PR TITLE
fibonacci.py

### PR DESCRIPTION
**Pull request by sandeepN06**
Generation of Fibonacci using Two Well Established Methods

### CODE REVIEW

**Comment by tasnimzotder** [comment]
@sandeepN06 Please rename the file from `Fibonacci.py` to `fibonacci.py`

**Comment by sandeepN06** [comment]
Yes done , please review :)

**Comment by tasnimzotder** [comment]
Well done @sandeepN06

**Review by tasnimzotder — APPROVED** [review]

**Comment by sandeepN06** [comment]
Thank you sir

**Comment by tasnimzotder** [comment]
Welcome :)

**Pull request merged**
