### PR TITLE
Add prime_check.cpp

### PR DESCRIPTION
**Pull request by Priyanshu729**
USING C++

### CODE REVIEW

**Comment by Priyanshu729** [comment]
Sir please accept my request

**Comment by Priyanshu729** [comment]
Is it ok??

**Review by tasnimzotder — APPROVED** [review]
Thanks @Priyanshu729 for your huge interest and contributions towards open source.
__Keep going ... 👨‍💻__

**Comment by Priyanshu729** [comment]
Thanks

**Comment by tasnimzotder** [comment]
> Is it ok??

Yes it's __OK__. Just I edited a little bit.

**Comment by tasnimzotder** [comment]
@Priyanshu729 You really have great passion and the ability for hard work.
You just need to focus and work hard on your work to bring it to a further distance.
We're here to learn from each other.

**Pull request merged**
