### PR TITLE
add Pratham's hackbar

### PR DESCRIPTION
**Pull request by praX03**

### CODE REVIEW

**Review by tasnimzotder — APPROVED** [review]

**Comment by tasnimzotder** [comment]
File already exists

**Comment by tasnimzotder** [comment]
You can open another PR with the `.cpp` file. Deleted the `.cpp` file by mistake as it was with the hackbar.

**Comment by praX03** [comment]
Hi, 
Would you be able to merge the LongestNonDecreasingSubSegment.CPP PR today. Since, it is the last day of Hacktober fest today.
Hope you understand!

**Comment by tasnimzotder** [comment]
Sure

**Pull request closed without merging**
