### PR TITLE
BFS Algorithm

### PR DESCRIPTION
**Pull request by kushalnl7**
Implementation of Depth First Search Algorithm in Python

### CODE REVIEW

**Comment by kushalnl7** [comment]
Hello sir, please review this pull request. It will help me for Hactoberfest PR challenge.

**Review by tasnimzotder — COMMENTED** [review]
hey @kushalnl7, your algorithm is `Breadth-first search (BFS)` or `Depth-first search (DFS)`?

**Comment by kushalnl7** [comment]
I am sorry. It's Breadth First Search. I uploaded it with wrong name. Should I push it again with right name and then create a Pull request?

**Comment by tasnimzotder** [comment]
Yes. You should correct it.
No need to create another `PR`.

**Comment by kushalnl7** [comment]
Yes, I did the changes.

**Review by tasnimzotder — APPROVED** [review]
Working

image

**Comment by tasnimzotder** [comment]
Thanks @kushalnl7, for your interest and contributions :)

**Comment by kushalnl7** [comment]
Thank You!

**Pull request merged**
