### PR TITLE
Fibonacci.py

### PR DESCRIPTION
**Pull request by Priyanshu729**

### CODE REVIEW

**Comment by tasnimzotder** [comment]
@Priyanshu729 Please delete `python/palindrome_checker.py` from your code and make a `commit`

**Comment by sandeepN06** [comment]
Hello Can You Help Me With Your Issue In This Please

**Comment by tasnimzotder** [comment]
Did you `delete` all the contents of `python/palindrome_checker.py`?

**Comment by sandeepN06** [comment]
Can I add Fibonacci using recursion too as its very helpful for people to hop and understand from the repository easily?

**Comment by tasnimzotder** [comment]
@rokibulislaam Check the conflicting file `python/palindrome_checker.py`.

**Pull request closed without merging**
